#!/usr/bin/env python3
"""Write a transparency sheet for one content bundle: every value, where it comes from, how sure.

Usage: python3 scripts/content_review_sheet.py <bundle-id>
Output: docs/content/<bundle-id>-review.md

Nobody has to approve a bundle (ADR-014): the automated evidence gate decides whether it runs.
The sheet shows what each value rests on. It lists each cited
parameter with its source, locator and certainty, every owner decision with its rationale,
each exercise with the sources behind its inclusion, and the validation result.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "core/python"))

from ai_trainer import content  # noqa: E402


def sheet(bundle_id: str) -> str:
    """The evidence sheet for ``bundle_id`` as Markdown."""
    manifest, body = content.all_bundles()[bundle_id]
    sources = manifest.get("sources") or {}
    problems = content.bundle_problems(manifest, body)
    parameters = content.cited_parameters(body)
    cited = [(path, value) for path, value in parameters if value["source"] != content.OWNER]
    owner = [(path, value) for path, value in parameters if value["source"] == content.OWNER]

    lines = [
        f"# Content evidence — `{manifest['id']}` ({manifest['version']})",
        "",
        "Generated by `scripts/content_review_sheet.py`; do not edit by hand.",
        "",
        f"- **Review state:** `{manifest['review']}`",
        f"- **Evidence basis:** {manifest['evidenceBasis']}",
        f"- **Validation:** {'passes' if not problems else f'{len(problems)} problem(s) — see below'}",
        f"- **Cited parameters:** {len(cited)} · **owner decisions:** {len(owner)}"
        f" · **exercises:** {len(body['exercises'])}",
        "",
        "## Sources",
        "",
    ]
    for key, source in sources.items():
        doi = f" doi:{source['doi']}" if source.get("doi") else ""
        read = ""
        if "fullTextRead" in source:
            read = " (full text read)" if source["fullTextRead"] else " (abstract only)"
        lines.append(f"- `{key}` — {source['citation']}{doi}{read}")
    lines += [
        "",
        "## Cited parameters",
        "",
        "| Parameter | Value | Source | Where | Certainty | Note |",
        "|---|---|---|---|---|---|",
    ]
    for path, value in cited:
        lines.append(
            f"| `{path}` | {_show(value['value'])} | `{value['source']}` | {value.get('locator', '')} "
            f"| {value.get('certainty', '')} | {value.get('note', '')} |"
        )
    lines += ["", "## Values no source gives a number for", ""]
    if owner:
        lines += ["| Parameter | Value | Rationale |", "|---|---|---|"]
        lines += [f"| `{path}` | {_show(value['value'])} | {value['rationale']} |" for path, value in owner]
    else:
        lines.append("None.")
    lines += [
        "",
        "## Exercises",
        "",
        "| Exercise | Role | Equipment | Alternatives | Sources |",
        "|---|---|---|---|---|",
    ]
    for exercise in body["exercises"]:
        cites = ", ".join(f"`{c['source']}` {c.get('locator', '')}".strip() for c in exercise.get("sources") or [])
        lines.append(
            f"| {exercise['name']} | {exercise['role']} | {exercise['equipmentKind']} "
            f"| {', '.join(exercise['alternatives']) or '—'} | {cites or '—'} |"
        )
    if problems:
        lines += ["", "## Validation problems", ""] + [f"- {problem}" for problem in problems]
    lines += [
        "",
        "## How this bundle goes live",
        "",
        "No person approves it (ADR-014). A bundle runs automatically when its `review` is `approved`",
        "(set once the research is complete, with a `verification` record) and the evidence gate finds",
        "no problem: every value cited or explained, every source peer-reviewed with a DOI or PMID and a",
        "qualifying design. A bundle that fails the gate never runs.",
        "",
    ]
    return "\n".join(lines)


def _show(value: object) -> str:
    return json.dumps(value) if isinstance(value, list | dict) else str(value)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: content_review_sheet.py <bundle-id>")
    bundle_id = sys.argv[1]
    target = ROOT / "docs/content" / f"{bundle_id}-review.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(sheet(bundle_id))
    print(f"Wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
